### ISSUE TITLE
deploy fails in Step 3 (again)

### ISSUE THREAD

**Issue by popas90** [googlecodelabs/smarthome-washer#10]
I'm getting the following error during deploy:

Error: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'databaseURL' of undefined
    at firebase.INTERNAL.registerService.Reference ([...]\smarthome-washer\washer-start\functions\node_modules\firebase\database-node.js:256:95)
    at Object.factories.(anonymous function) [as database] ([...]\smarthome-washer\washer-start\functions\node_modules\firebase\app\firebase_app.js:245:32)
    at FirebaseAppImpl.getService ([...]\smarthome-washer\washer-start\functions\node_modules\firebase\app\firebase_app.js:108:78)
    at Object.serviceNamespace [as database] ([...]\smarthome-washer\washer-start\functions\node_modules\firebase\app\firebase_app.js:263:40)
    at Object.<anonymous> ([...]\smarthome-washer\washer-start\functions\index.js:26:30)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

More info:

npm --version
5.6.0

node --version
v8.11.4

package.json:
{
  "name": "smarthome-washer",
  "description": "Codelab for controlling devices through the Google Assistant",
  "engines": {
    "node": "8"   **-> changed this one from 6 to 8, didn't help**
  },
  "dependencies": {
    "actions-on-google": "^2.2.0",  **-> tried removing all "^", didn't help**
    "cors": "^2.8.4",
    "firebase": "^4.0.0",
    "firebase-admin": "^5.13.0",
    "firebase-functions": "^2.0.0",
    "googleapis": "^27.0.0"
  },
  "private": true,
  "devDependencies": {
    "eslint": "^4.19.1",
    "eslint-config-google": "^0.9.1"
  }
}

Thanks!

**Comment by Fleker** [comment]
Line 26:

`const firebaseRef = firebase.database().ref('/');`

So it seems to suggest that the variable `firebase` is undefined. It is declared on line 22:

`const firebase = require('firebase');`

Have you run `npm install` in this directory?

**Comment by popas90** [comment]
I believe that was the problem. Installed firebase locally in the project folder and it worked. Thanks!

**Comment by popas90** [comment]
Closed by mistake, still need to try this out.

**Comment by popas90** [comment]
This is the output from running "npm install" in the functions directory:

> grpc@1.10.1 install /home/popas/Code/smarthome-washer/washer-start/functions/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

make: Entering directory '/home/popas/Code/smarthome-washer/washer-start/functions/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
make: Entering directory '/home/popas/Code/smarthome-washer/washer-start/functions/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
make: Leaving directory '/home/popas/Code/smarthome-washer/washer-start/functions/node_modules/grpc/build'
Failed to execute '/usr/bin/node /home/popas/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/popas/Code/smarthome-washer/washer-start/functions/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/popas/Code/smarthome-washer/washer-start/functions/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
make: Leaving directory '/home/popas/Code/smarthome-washer/washer-start/functions/node_modules/grpc/build'

**Comment by Fleker** [comment]
Okay, so this works, but I can't determine why

```
const firebase = require('firebase');
const admin = require('firebase-admin');
// Initialize Firebase
firebase.initializeApp(JSON.parse(process.env.FIREBASE_CONFIG));
```

**Comment by Fleker** [comment]
Okay that seems like the [canonical](https://firebase.google.com/docs/database/extend-with-functions) way to initialize functions to connect to Firebase.

**Comment by popas90** [comment]
Thanks a lot, it worked!
