### ISSUE TITLE
Step 3: click `[test] My Washer` didn't return a list of devices

### ISSUE THREAD

**Issue by li2** [googlecodelabs/smarthome-washer#13]
Firebase deploy completed (in `washer-done` directory),
My configurations in the Actions on Google console are:

Fulfillment URL: `<Hosting URL>/smarthome`
Client ID: ABC123
Client secret: DEF456
Auth URL: `<Hosting URL>/fakeauth`
Token URL: `<Hosting URL>/faketoken`

Hosting URL is `https://<my-project-id>.firebaseapp.com`

But when I click `[test] My Washer` on Assistant settings menu on my Pixel Phone, it didn't return a list of devices, it showed the webpage of hosting URL, I cannot link to the Google Assistant:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6058601/50463867-233d7580-09e2-11e9-8ebc-e2d9ef7d1c68.gif)

Please help, thanks!

**Comment by Fleker** [comment]
Are you using the latest version of the project code? In your `index.js`, do you see a device being returned in the SYNC response?

Can you check the logs to see if everything is working correctly?
