### ISSUE TITLE
Build fails at step 3 - Error on actions for google webpage

### ISSUE THREAD

**Issue by nickimola** [googlecodelabs/smarthome-washer#15]
Hi

I've just cloned this project and have been following the tutorial step by step, but when i try to start the test in the simulator (as mentioned in the tutorial) i get this error:

> GoogleFulfillment 'actions.fulfillment.devices' is not supported

and therefore i can't carry on with the guide.

node v: 6.12.3
npm v: 3.10.10
firebase v: 6.3.1

**Comment by Fleker** [comment]
Seems related to https://github.com/actions-on-google/smart-home-nodejs/issues/286

**Comment by psrangdal** [comment]
Any update on this error? I am involved in the design and architecture of the google smarthome for whirlpool appliances and our development has taken been hit for this error... 
/Pradeep Rangdal

**Comment by Fleker** [comment]
Testing smart home projects has been resolved.
