### ISSUE TITLE
firebase use -add error:Server Error. read ECONNRESET

### ISSUE THREAD

**Issue by lichongting** [googlecodelabs/smarthome-washer#16]
when i follow step 3 and use "firebase use -add", there was an error:
Server Error. read ECONNRESET
My firebase-debug.log is ``

[debug] [2019-03-01T01:56:57.906Z] ----------------------------------------------------------------------
[debug] [2019-03-01T01:56:57.908Z] Command:       D:\Program Files (x86)\nodejs\node.exe C:\Users\chongting.li\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js use --add
[debug] [2019-03-01T01:56:57.908Z] CLI Version:   6.4.0
[debug] [2019-03-01T01:56:57.909Z] Platform:      win32
[debug] [2019-03-01T01:56:57.909Z] Node Version:  v10.15.0
[debug] [2019-03-01T01:56:57.913Z] Time:          Fri Mar 01 2019 09:56:57 GMT+0800 (GMT+08:00)
[debug] [2019-03-01T01:56:57.913Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-03-01T01:56:57.938Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-03-01T01:56:57.940Z] > authorizing via signed-in user
[debug] [2019-03-01T01:56:57.948Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects  
 
[debug] [2019-03-01T01:57:37.691Z] Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
[error] 
[error] Error: Server Error. read ECONNRESET

**Comment by Fleker** [comment]
Have you first run `firebase login`? It seems like you need to first enable certain permissions for this tool.
