### ISSUE TITLE
Step 3: cannot open washer page

### ISSUE THREAD

**Issue by thangta** [googlecodelabs/smarthome-washer#17]
Firebase deploy completed (in washer-done directory),
But when I click [test] app on Assistant settings menu, it didn't return a washer webpage, it only showed the white page and text "Accounts now linked". 

![image](https://user-images.githubusercontent.com/13417944/53937016-61d86600-40de-11e9-9914-ac528fe316d4.png)

**Comment by Fleker** [comment]
Does your fulfillment have an `onSync` function that implements a washer payload, like in [the code](https://github.com/googlecodelabs/smarthome-washer/blob/master/washer-start/functions/index.js#L66)?

**Comment by thangta** [comment]
Hi. Sorry i am not getting your idea. Where can i put that code, any way on dialogs console?.  
I just following exactly your guidelines: firebabe deploy the washer-start folders and I can see 5 function created in firebase console.

**Comment by Fleker** [comment]
If you look at the Firebase console, going to the Firebase logs, do you see the onSync function run? Maybe the function didn't respond in the app due to a slow execution time as the function had a cold start? The function should return a device, which you should then see.

**Comment by thangta** [comment]
Here is the log. I don't see onSync function run, just only fakeauth and faketoken
[Uploading image.png…]()

**Comment by Fleker** [comment]
Maybe if you try once or twice in a row, it'll allow the function to start up and be more responsive. If the account linking worked, then the syncing should also succeed.

**Comment by thangta** [comment]
I have been try more than ten time. But just only get same white page.

**Comment by thangta** [comment]
Here is the my linking process. 
First time, I click on my app and do nothing -> it auto back to main menu. 
Second time, I clink on my app and keep hold my finger -> the webpage stop at white page. 
I am using android 9
  

![ezgif-1-55e393e6e0cb](https://user-images.githubusercontent.com/13417944/53972021-9d038500-4130-11e9-8207-f64fb0188943.gif)

**Comment by Fleker** [comment]
Is your smart home action fulfillment pointing to the correct URL? Maybe you should make sure. I'm not too sure why you aren't getting a request to your fulfillment endpoint.

**Comment by thangta** [comment]
Following your guide.  put fulfillment URL in smarthome action: 
![image](https://user-images.githubusercontent.com/13417944/53995225-00100e80-4167-11e9-8b80-b85cb016189c.png)


![image](https://user-images.githubusercontent.com/13417944/53994994-5892dc00-4166-11e9-9816-8f681dd9ae48.png)

**Comment by Fleker** [comment]
After you change the URL, try to disable and re-enable testing. Maybe the URL needs to be reconfigured in the console

**Comment by thangta** [comment]
It still not working. 
I try to test with following Sinric project, Google home can load the web page. Check pls
https://github.com/kakopappa/sinric/wiki/How-to-use-Google-Home

**Comment by thangta** [comment]
> If you look at the Firebase console, going to the Firebase logs, do you see the onSync function run? Maybe the function didn't respond in the app due to a slow execution time as the function had a cold start? The function should return a device, which you should then see.

Hi, You say that the execution time is slow, that why i can't see the return page. Could you double check your instruction. I was re-initialed this project many time but still get same issues, even change nodejs version, reset action on google, change to another account,...

**Comment by Fleker** [comment]
I've run through the instructions without issue. I'm not sure why you're seeing the issue you are.
