### ISSUE TITLE
Step 3 of Codelab mentions 3 folders in zip file when there are only 2

### ISSUE THREAD

**Issue by hcalzada** [googlecodelabs/smarthome-washer#18]
Step 3 of Codelab mentions 3 folders in zip file when there are only 2:s

washer-start
washer-done
![2019-04-02_16-08-22](https://user-images.githubusercontent.com/28028879/55442040-d974a600-5561-11e9-928e-47b2170d2462.png)

**Comment by Fleker** [comment]
Thank you for finding this. This will be fixed soon.
