### ISSUE TITLE
codelab tutorial is not complete

### ISSUE THREAD

**Issue by ColbyMaloy** [googlecodelabs/smarthome-washer#19]
on step 3, after calling firebase deploy we're told to "Configure your project in the Actions on Google console"

we're then shown a photo of "account linking(optional)"

this photo lead me to believe it was an optional step when in fact it is not optional. not to mention you have to click on "Overview" before seeing the account link option.

then you're also required to give "invocation" a name, which the codelab doesnt mention

then we are told
Enter the following client information:

Client ID | ABC123
-- | --
Client secret | DEF456

...click save

but there are also 2 additional fields before being able to click save.

was hoping someone could improve the clarity of step 3. i was stuck not being able to retrieve the washer for some time.

**Comment by Fleker** [comment]
The invocation name should not be required, as "My Test App" is the default name for it.

The codelab instructs one to input the client ID and secret, as well as two additional URLs, which is shown in the screenshot.

What part of the instructions seemed to be unclear?
