### ISSUE TITLE
tunnel xyz123.ngrok.io not found

### ISSUE THREAD

**Issue by pawanmlnr** [googlecodelabs/smarthome-washer#2]
tunnel xyz123.ngrok.io not found error on connecting app

**Comment by Fleker** [comment]
Where do you encounter this error? This codelab should not be using ngrok at all.

**Comment by markone67** [comment]
xyz123.ngrok.io is a fake name for a real url that is dynamically created when you use ngrok libraries in your project. Basically you add ngrok on your code, run on local machine and NEW tunnel will be created with unique name (similar to ddns facility).

Said that, that project doesn't use ngrok facility, unless you add it!

**Comment by Fleker** [comment]
I am aware of what ngrok is, which is why I'm confused by OP's issue.
