### ISSUE TITLE
onWrite() function need to be updated

### ISSUE THREAD

**Issue by MengHuanLee** [googlecodelabs/smarthome-washer#20]
The section of "Add API Call" here in this page,
https://codelabs.developers.google.com/codelabs/smarthome-washer/index.html#9
The onWrite() function has been updated and takes two parameters.
Need to be fixed or the report function does not work.

**Comment by Fleker** [comment]
`event.params` => `context.params`
`event.val()` => `snapshot.val()` or stay as-is
