### ISSUE TITLE
No toggle in home app

### ISSUE THREAD

**Issue by kiralikbeyin** [googlecodelabs/smarthome-washer#21]
I see washer in android home app (with a gear on right top)  when i click on it it goes to device settings. There is nothing about on-off, turbo etc.

Is this normal?

![image](https://user-images.githubusercontent.com/10079333/58707343-520aae00-83bd-11e9-9d77-57c3a04950d6.png)

**Comment by kiralikbeyin** [comment]
Same problem here : https://support.google.com/googlehome/thread/570067?hl=en

**Comment by Fleker** [comment]
Yes this is the current expected user interface.

**Comment by kiralikbeyin** [comment]
Ok, how can i add on-off? Is it possible?

**Comment by Fleker** [comment]
The [touch controls documentation](https://developers.google.com/actions/smarthome/develop/touch-controls) lists the traits that have touch controls.

**Comment by kiralikbeyin** [comment]
@Fleker 

So we control only these **Supported device types**
Camera
Light
Lock (Smart displays only)
Outlet
Switch
Thermostat

**Supported traits**
CameraStream
OnOff
TemperatureSetting


Please add more types like shutter, curtain, blind devices with adjustable percentage like brightness of light. For example a window shutter can be opened in 10 seconds. If i adjust it to %80 it works 8 seconds and shutter state will be %80 opened/closed.

+ I really want to help for Turkish language translation if you want. Home app doesnt support all languages so adding more touch controls will solve language problem.

I have a 4 gang switch (one device), how can i add one device with 4 switches?

I worked on homekit devices and every device can be really controlled with touch.

**Comment by Fleker** [comment]
If you have one device with four switches, it may be preferable to add them as four independent switches for easier control.
