### ISSUE TITLE
Users Auth

### ISSUE THREAD

**Issue by kiralikbeyin** [googlecodelabs/smarthome-washer#23]
@Fleker Please can you make a tutorial about  authentication with auth0 or google sign in?

https://medium.com/google-developers/authenticating-smart-home-actions-for-the-google-assistant-with-auth0-b6fda3d2ee3d didnt worked for me. When i try to link account with phone it returns to same screen "manage accounts" (must go to auth0 login page)

edit: i see "account now linked" (1 second)  in https://asistant.google.com when i click test[account]

**Comment by Fleker** [comment]
The Medium post you link to is the tutorial I made about authentication with Auth0. I got the integration to work, so I'm not sure what may be the specific issue.

**Comment by kiralikbeyin** [comment]
its for firestore nor for realtime db

**Comment by Fleker** [comment]
This is true, but it shouldn't be too difficult to update the user ID functions to use the realtime database instead. All the Auth0 setup should be the same.

**Comment by kiralikbeyin** [comment]
i am trying to install https://github.com/actions-on-google/smart-home-nodejs so i can follow your Medium post to understand how its done.

I already updated user ID functions, but my main problem is:
When i try to link account with phone it returns to same screen "manage accounts" never saw auth0 login

**Comment by Fleker** [comment]
The auth and token URLs would need to be updated to point to the Auth0 URLs. You may need to disconnect and reconnect for it to work as expected, as well as disabling/enabling testing.

**Comment by kiralikbeyin** [comment]
Waaaaww i made only disconnect but unlinking the "TEST" solves the problem!

Thank you!

**Comment by kiralikbeyin** [comment]
@Fleker auth0.com doesnt "really" work with google. Everything is fine with only "developer-test keys".
 
When i create a real clientID and secret from gcp and use it in auth0.com i never saw login screen. Only way is to disable and enable google login in auth0.com and login in 2-3 minutes. After 5 minutes later unlink and relink (tried with 3 different gmail accunts) i cant see login screen again and turns back to google home.

Please can you make a new blog or show me a simple auth system alternative?

**Comment by Fleker** [comment]
I don't know why Auth0 wouldn't work in a production environment. Does Auth0 work fine if you do it directly outside of the Google Home app?

**Comment by devunwired** [comment]
Closing this issue as unrelated to the codelab. For general development questions on Google smart home, feel free to post on our community forums:
- Reddit: https://www.reddit.com/r/GoogleAssistantDev/
- StackOverflow: https://stackoverflow.com/questions/tagged/google-smart-home
