### ISSUE TITLE
Report state on screen

### ISSUE THREAD

**Issue by kiralikbeyin** [googlecodelabs/smarthome-washer#24]
![image](https://user-images.githubusercontent.com/10079333/59617594-480fdb80-912f-11e9-8e79-9dc844ee8b3e.png)
When i change OnOff value to true or false (from firebase or web update) it doesnt sync immediately on this screenshot.
Go back to home screen an re enter to device show updated value no problem.

How can i see device position immediately?

**Comment by Fleker** [comment]
This is an application limitation.
