### ISSUE TITLE
Question - Push notification & security system

### ISSUE THREAD

**Issue by kiralikbeyin** [googlecodelabs/smarthome-washer#25]
@Fleker Is there any way to send push notification using gcm?
I added a virtual security system, searched for motion-door windows sensors but they are not available...

Is there any plan for adding security system to touch control?
Arm - Disarm like on off maybe... (becuase i have to arm-disarm by talking to asistant which has a language limit)

**Comment by Fleker** [comment]
No, there is no push notification functionality. If you want to notify a change in the device state, you would use [report state](https://developers.google.com/actions/smarthome/develop/report-state).

I can't provide a timeline on adding touch controls for specific traits.

**Comment by kiralikbeyin** [comment]
Thank you, it is good to know about push notifications.

I will go with this

when ```exports.reportstate = functions.database.ref("washer").onWrite(async (change, context) => {...```finished; simple "subscripe to topic" mobile app will be a solution.

````
const functions = require('firebase-functions');
const admin = require('firebase-admin');

admin.initializeApp(functions.config().firebase);

//Now we're going to create a function that listens to when a 'Notifications' node changes and send a notificcation
//to all devices subscribed to a topic

exports.sendNotification = functions.database.ref("Notifications/{uid}")
.onWrite(event => {
    //This will be the notification model that we push to firebase
    var request = event.data.val();

    var payload = {
        data:{
          username: request.username,
          imageUrl: request.imageUrl,
          email: request.email,
          uid: request.uid,
          text: request.text
        }
    };

    //The topic variable can be anything from a username, to a uid
    //I find this approach much better than using the refresh token
    //as you can subscribe to someone's phone number, username, or some other unique identifier
    //to communicate between

    //Now let's move onto the code, but before that, let's push this to firebase

    admin.messaging().sendToTopic(request.topic, payload)
    .then((response) => {
        console.log("Successfully sent message: ", response);
        return true;
    })
    .catch((error) => {
        console.log("Error sending message: ", error);
        return false;
    })
})
//And this is it for building notifications to multiple devices from or to one.
`````

There is huge blank for security system, i hope you fill it fast so no need 3.party solutions and manage everything from Google Home.
We need more touchable devices.

Thanks again.
