### ISSUE TITLE
Is ReportState stored in Firebase?

### ISSUE THREAD

**Issue by javiercuellar73** [googlecodelabs/smarthome-washer#30]
Hi.

I followed all steps of washer demo and is working, but I really don't fully understand the reportstate function from step 10. The logic says that it will be triggered when firebase is written and will call "app.reportState" to update HomeGraph.  That is what I understand. 

But I did this example.
1. Remove the reportstate trigger from step 10 (no  app.reportState  is called)
2. Manually update firebase database.
3. Ask googlehome if light is on, and it answers correctly based on the status of firebase. Of course, this is true because "app.onQuery" retrieve status from firebase.

With that in mind, when app.OnExecute is called,  firebase is updated.  When I ask for light status, app.onQuery retrieve status from firebase....   so, what is   "app.reportState(postData)" used for?  Is HomeGraph database same as firebase database?

Thanks for any clarification.

**Comment by Fleker** [comment]
As the [the documentation](https://developers.google.com/actions/smarthome/develop/report-state):

> Report State reports to Google the states of user devices with the specified agentUserId associated with them (sent in the original SYNC request). When the Google Assistant wants to take an action that requires understanding the current state of a device, it can simply look up the state information in the Home Graph instead of issuing a QUERY intent to various third-party clouds prior to issuing the EXECUTE intent.

So if you were to change the light brightness, the brightness can be obtained in the Home Graph instead of querying and then executing a brightness command.
