### ISSUE TITLE
Devices are not showing up

### ISSUE THREAD

**Issue by aizazhussain341** [googlecodelabs/smarthome-washer#33]
i followed the following tutorial by https://codelabs.developers.google.com/codelabs/smarthome-washer/#0
from start to end as it is but when i click on my [test] My App it redirects me to the same page (Add devices) and nothing happens. Also not a single device is shown in google home app

**Comment by devunwired** [comment]
Have you tried this flow from different Android/iOS devices? Do you get the same behavior across them all?

You should also check in the [StackDriver logs](https://developers.google.com/assistant/smarthome/develop/error-logging) for your Actions project to see if any errors are being reported.

**Comment by ChinthakaJay** [comment]
Got the same issue. Any update?

`D 2020-04-17T06:29:59.914250036Z fakeauth 8po8aa3o6puf Function execution started fakeauth 8po8aa3o6puf 

I 2020-04-17T06:29:59.925Z fakeauth 8po8aa3o6puf https://oauth-redirect.googleusercontent.com/r/smarthomeproject-for-cod-143f2?code=xxxxxx&state=AFVGnUG9j4a3s78K-DHsFDHfp8OzUmLOiIa92Dsjtep-XeLD2I2Djey6XBZndMLcJQYxHRkwMgqT900u4M4fGW_LTH3BMdMZ12YcSqvihG8BKmYx1qN4M6ySEFgtzS4yVyZPSaHBMtrXM0JioqlbyTioW3ebEqIQkp9huYq-uh_LYeakNbGQqbO1jFGl_2K74ITCEqcndwiD3nzrDivWT4q7Yyf0BfLy5rEzSeFFAs0EGLJPekSVz3MlPME8DYPXaaGeoH1zlcl1jemw5WCt9jzlzxQZwKePXCgCkeBGiEgniO8ksekC8o6dm_arfC1DnBUh4xutEjV7PIvuZcjr-p3e3N3UeKIkai19x_91e6a4fqSY7YDQdlH9gEenamPe969OvwvEnIrZghfw8QxHdRljaxlN83JQPQAPc39DJxM8a9lSanCHBIFC9EF_hqMJQsBlGvhP6GzS1k0QdSHziPO1CfiifO7Q_-xbRVnSniYdInBdehHq2buf1IQ9sKkyk6Kw2ulwqLx_k4ZpiNPmcqRcP8lz2J09iWzhWsxeEAtv1ZDgV4ktHTgkdxjOLEbS498PKy3w_vi__zyC2aH8QH9JvrGAB6M1csT2cqbEYPYkxMpnxqQUD3PHrsqe8A_3-R6hfZknTLIkgxxVrq7bcmc_NKAsORByd3gT-JIbtrl5K2AybxOrkB6DOADAoPO1y143yIElYFP7 fakeauth 8po8aa3o6puf 

D 2020-04-17T06:29:59.928137243Z fakeauth 8po8aa3o6puf Function execution took 14 ms, finished with status code: 302 fakeauth 8po8aa3o6puf 
  undefined
`

Can see these log entries in the logs.

**Comment by devunwired** [comment]
We have observed this happening on some devices when there is no authorization UI presented, so we've added a fake login page to the codelab project to address this. Feel free to open a new issue if you are still experiencing the problem with the updated code.

Fixed with a1d4102f12e4e31aac0e550d5ad730fab6d70529
