### ISSUE TITLE
Tunnel ---------ngrok.io not found

### ISSUE THREAD

**Issue by SHEEPHEAD221** [googlecodelabs/smarthome-washer#34]
I am trying out hidden eye from GitHub as a test with my friends. Hidden eye works like this it makes a fake login page and then uses ngrok to forward this it people outside your network. When my friend does it works but when I ask him to run for example 2107f2ac.ngrok.io it says Tunnel 79cd0b59.ngrok.io not found. I have restarted, reinstalled and done everything under the moon. I thought that ngrok passes firewalls but my only guess is maybe my firewall is blocking it so I added a firewall exception of the ngrok port but it still does not work. Please help

**Comment by devunwired** [comment]
This codelab does not use ngrok, and this question does not seem to be related to the code in this repository. If you have a general development question about Google Smart Home, please post it on [StackOverflow](https://stackoverflow.com/questions/tagged/google-smart-home).
