### ISSUE TITLE
"Await" Errors in building Washer

### ISSUE THREAD

**Issue by HowardHonig** [googlecodelabs/smarthome-washer#43]
There are so many errors in this example it's hard to get through.

My latest is index.js contains the statement:  await Promise.all(queryPromises) (line 278)
Deploying gives the error:  SyntaxError: await is only valid in async functions and the top level bodies of modules

Which is true.  Couldn't find the Promise function to change it.  I suspect this worked with an earlier version of node.js, but wish the example kept up with the node.js versions.

So, how should this be fixed?

Another error, which I figured out, was to get the => arrow functions to 2019 in the eslint config  ECMAScript tag.  Took a few hours to figure that one out.

**Comment by Fleker** [comment]
The SyntaxError suggests your function does not have an `async` keyword at the start, which is required for every asynchronous section of code.

For example:

```
exports.reportstate = functions.database.ref('{deviceId}').onWrite(async (change, context) => {
    // ...
})
```

The `async` keyword needs to be declared before you can sue any `await`. It also needs to be declared for any smaller blocks of code within this top-level function.

**Comment by HowardHonig** [comment]
Ok, thanks.  I get it, the async needs to be specified at the start of the function that contains the "await".  This tells the java interpreter that the whole function is asynchronous.  Cool.  Thanks again.

Since this code was downloaded from the https://codelabs.developers.google.com/codelabs/smarthome-washer#2 example, I suggest the omission of the async keyword is an error.

**Comment by Fleker** [comment]
Can you point to the section of code that is having this issue?

**Comment by HowardHonig** [comment]
Whoops, my bad.  On the download code all the app.onXYZ functions except "updateDevice" do not have the async directive.  When I copied the code fragments update in the instructions (which is very well written), just the body of the function was copied/typed.  The code fragments correctly show the async if there is an await statement in the body.   I totally missed that.  The code fragments are correct.

I'm sorry for the oversite and regret my error.  In my defense I'm new to node.js but making progress.

**Comment by Fleker** [comment]
It's great that you figured it out. Happy to help!
