### ISSUE TITLE
Where is the image defined that the washer displays in Google Home?

### ISSUE THREAD

**Issue by HowardHonig** [googlecodelabs/smarthome-washer#44]
This is not a bug, but the question is related to the washer example.  
Where is the image defined/identified that shows up in Google Home once the device is linked successfully?   I spent time reading the documents but didn't find the answer to this.  I'm just looking for a link to a webpage that can explain how to make my own.

Thank you in advance.

**Comment by Fleker** [comment]
This icon is provided as part of the Home app, and not something that you can provide.

**Comment by HowardHonig** [comment]
Fleker, I know you must be busy but what a lazy answer.  What I was looking for is HOW the image is selected and where in the code.  I found it under touch controls by doing a lot of research, a lot more than I would have liked if someone would have answered it properly.  You could have just said "this is provided in "touch controls".  As it is, touch controls is very buggy not displaying the correct image in Google Home app when the control is selected.  Maybe you are too busy to fix the issues, let alone answer a simple question.
