### ISSUE TITLE
The route of Token URI described in step 3 doesn't match the code

### ISSUE THREAD

**Issue by eric30** [googlecodelabs/smarthome-washer#5]
The endpoint of Token URL described in step 3 of the codelab is 

https://us-central1-project-id.cloudfunctions.net/authtoken

However, the route (/authtoken) is different than [what it's defined](https://github.com/googlecodelabs/smarthome-washer/blob/master/washer-start/functions/index.js#L38) in washer-start & washer-done projects, so it would cause account linking failure.

**Comment by Fleker** [comment]
The codelab has been updated with the correct URL.
